version: '3'
networks:
  rabbitmq_go_net:
    driver: bridge
services:
  rabbitmq:
    image: "rabbitmq:3.13-rc-management"
    container_name: rabbitmq_container
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest  
    networks:
      - rabbitmq_go_net
  
  student:
    build:
      context: .
      dockerfile: Dockerfile_student
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  module_coordinator:
    build:
      context: .
      dockerfile: Dockerfile_modCo
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  teaching_assistant:
    build:
      context: .
      dockerfile: Dockerfile_TA
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  dm_demo:
    build:
      context: .
      dockerfile: Dockerfile_DM
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  cc_demo:
    build:
      context: .
      dockerfile: Dockerfile_CC
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net